Fix bug in network_graph.py
Fix AttributeError: module 'matplotlib.cbook' has no attribute 'iterable' when running draw_networkx_edges(). I think what happened was matplotlib retired its cb.iterable and it doesn't exist in the newest version. Switching to np.iterable solves the problem. 

p.s. You asked to me to do this pull request months ago but I totally forgot about it. It came up just again when I was starting a new repo, so here it is. Sorry for the delay!